version: '3.3'
services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    container_name: nginx
    depends_on:
      - client
      - backend
    ports:
      - "80:80"
    
  client:
    build:
      dockerfile: Dockerfile.dev
      context: client/
    container_name: client
    env_file:
      - env/client.env
    volumes:
      - /app/node_modules
      - ./client:/app

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: backend/
    container_name: backend
    env_file:
      - env/backend.env
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./backend:/app

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres_dev_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env


  