version: '3.3'
services:
    
  client:
    build:
      dockerfile: Dockerfile.dev
      context: client/
    container_name: client
    env_file:
      - env/client.env
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: backend/
    container_name: backend
    env_file:
      - env/backend.env
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "1337:1337"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres_dev_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env


  