version: '3.3'
services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    container_name: nginx
    depends_on:
      - client
      - backend
    ports:
      - "80:80"
    
  client:
    build:
      dockerfile: Dockerfile
      context: client/
    container_name: client
    env_file:
      - env/client.env

  backend:
    build: 
      dockerfile: Dockerfile
      context: backend/
    container_name: backend
    env_file:
      - env/backend.env